wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.10.0
    start_time: 1726410367.265736
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 53
      - 55
      3:
      - 7
      - 23
      4: 3.10.0
      5: 0.13.3
      8:
      - 3
      - 5
augmentation_config/random_crop:
  desc: null
  value: true
augmentation_config/random_cut:
  desc: null
  value: true
augmentation_config/random_flip:
  desc: null
  value: true
augmentation_config/random_intensity_scale:
  desc: null
  value: false
augmentation_config/random_noise:
  desc: null
  value: false
augmentation_config/random_rotate:
  desc: null
  value: true
bands:
  desc: null
  value: 224
batch_size:
  desc: null
  value: 64
camera_agnostic_num_gauss:
  desc: null
  value: 5
camera_type:
  desc: null
  value: CameraType.VIS
classification_type:
  desc: null
  value: ClassificationType.RIPENESS
comment:
  desc: null
  value: None
data_path:
  desc: null
  value: D:\College\Project
debug:
  desc: null
  value: false
fruit:
  desc: null
  value: Fruit.MANGO
git_id:
  desc: null
  value: e74580eea097ac4af5f40b10344603c5fb7e93a3
hidden_layers:
  desc: null
  value:
  - 25
  - 30
  - 50
input_size:
  desc: null
  value:
  - 64
  - 64
log_path:
  desc: null
  value: None
lr:
  desc: null
  value: 0.01
model:
  desc: null
  value: deephs_net
model_checkpoint:
  desc: null
  value: None
num_classes:
  desc: null
  value: 3
num_epochs:
  desc: null
  value: 5000
num_workers:
  desc: null
  value: 4
online_logging:
  desc: null
  value: true
seed:
  desc: null
  value: 23312323
slurm_job_id:
  desc: null
  value: Hut:C:\Users\intha\deephs_fruit
slurm_job_path:
  desc: null
  value: ''
test_augmentation:
  desc: null
  value: true
tta_augmentation_config/random_crop:
  desc: null
  value: false
tta_augmentation_config/random_cut:
  desc: null
  value: false
tta_augmentation_config/random_flip:
  desc: null
  value: true
tta_augmentation_config/random_intensity_scale:
  desc: null
  value: false
tta_augmentation_config/random_noise:
  desc: null
  value: false
tta_augmentation_config/random_rotate:
  desc: null
  value: true
tta_augmentation_iterations:
  desc: null
  value: 5
type:
  desc: null
  value: single_camera
wavelengths:
  desc: null
  value:
  - 397.66
  - 400.28
  - 402.9
  - 405.52
  - 408.13
  - 410.75
  - 413.37
  - 416.0
  - 418.62
  - 421.24
  - 423.86
  - 426.49
  - 429.12
  - 431.74
  - 434.37
  - 437.0
  - 439.63
  - 442.26
  - 444.89
  - 447.52
  - 450.16
  - 452.79
  - 455.43
  - 458.06
  - 460.7
  - 463.34
  - 465.98
  - 468.62
  - 471.26
  - 473.9
  - 476.54
  - 479.18
  - 481.83
  - 484.47
  - 487.12
  - 489.77
  - 492.42
  - 495.07
  - 497.72
  - 500.37
  - 503.02
  - 505.67
  - 508.32
  - 510.98
  - 513.63
  - 516.29
  - 518.95
  - 521.61
  - 524.27
  - 526.93
  - 529.59
  - 532.25
  - 534.91
  - 537.57
  - 540.24
  - 542.91
  - 545.57
  - 548.24
  - 550.91
  - 553.58
  - 556.25
  - 558.92
  - 561.59
  - 564.26
  - 566.94
  - 569.61
  - 572.29
  - 574.96
  - 577.64
  - 580.32
  - 583.0
  - 585.68
  - 588.36
  - 591.04
  - 593.73
  - 596.41
  - 599.1
  - 601.78
  - 604.47
  - 607.16
  - 609.85
  - 612.53
  - 615.23
  - 617.92
  - 620.61
  - 623.3
  - 626.0
  - 628.69
  - 631.39
  - 634.08
  - 636.78
  - 639.48
  - 642.18
  - 644.88
  - 647.58
  - 650.29
  - 652.99
  - 655.69
  - 658.4
  - 661.1
  - 663.81
  - 666.52
  - 669.23
  - 671.94
  - 674.65
  - 677.36
  - 680.07
  - 682.79
  - 685.5
  - 688.22
  - 690.93
  - 693.65
  - 696.37
  - 699.09
  - 701.81
  - 704.53
  - 707.25
  - 709.97
  - 712.7
  - 715.42
  - 718.15
  - 720.87
  - 723.6
  - 726.33
  - 729.06
  - 731.79
  - 734.52
  - 737.25
  - 739.98
  - 742.72
  - 745.45
  - 748.19
  - 750.93
  - 753.66
  - 756.4
  - 759.14
  - 761.88
  - 764.62
  - 767.36
  - 770.11
  - 772.85
  - 775.6
  - 778.34
  - 781.09
  - 783.84
  - 786.58
  - 789.33
  - 792.08
  - 794.84
  - 797.59
  - 800.34
  - 803.1
  - 805.85
  - 808.61
  - 811.36
  - 814.12
  - 816.88
  - 819.64
  - 822.4
  - 825.16
  - 827.92
  - 830.69
  - 833.45
  - 836.22
  - 838.98
  - 841.75
  - 844.52
  - 847.29
  - 850.06
  - 852.83
  - 855.6
  - 858.37
  - 861.14
  - 863.92
  - 866.69
  - 869.47
  - 872.25
  - 875.03
  - 877.8
  - 880.58
  - 883.37
  - 886.15
  - 888.93
  - 891.71
  - 894.5
  - 897.28
  - 900.07
  - 902.86
  - 905.64
  - 908.43
  - 911.22
  - 914.02
  - 916.81
  - 919.6
  - 922.39
  - 925.19
  - 927.98
  - 930.78
  - 933.58
  - 936.38
  - 939.18
  - 941.98
  - 944.78
  - 947.58
  - 950.38
  - 953.19
  - 955.99
  - 958.8
  - 961.6
  - 964.41
  - 967.22
  - 970.03
  - 972.84
  - 975.65
  - 978.46
  - 981.27
  - 984.09
  - 986.9
  - 989.72
  - 992.54
  - 995.35
  - 998.17
  - 1000.99
  - 1003.81
